version: '3.8'
services:
  db:
    image: postgres:15
    container_name: nest_task_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: nest_task_app
    restart: on-failure
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pgdata:
